# Generated by Django 4.0.5 on 2025-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatentMS', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
