# Generated by Django 4.0.5 on 2025-07-23 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatentMS', '0007_alter_category_slug_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-likes', '-views', 'name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-views', 'title'], 'verbose_name': '页面', 'verbose_name_plural': '页面'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatentMS.category', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=128, verbose_name='页面标题'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(verbose_name='页面URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='个人网站'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('category', 'title')},
        ),
    ]
